language: ruby
os:
  - osx
install:
  - brew update
  - brew --version
  - brew install zsh
  - zsh --version
  - git clone --depth 1 https://github.com/robbyrussell/oh-my-zsh.git test/oh-my-zsh
  - cd test/oh-my-zsh && git rev-parse HEAD
script:
  - ZDOTDIR=$PWD/test ZSH=$PWD/test/oh-my-zsh zsh -cli 'exit 0'
notifications:
  slack:
    secure: aZ49kRCkDnXq13+DeHwAa18EsMgGhTsijcw3wHcCd13MSYcFWebmuVEjZ30hq/+8u+EQwaH7bxbhRv8cMNN3Ln0WWBOj7GmfubLIJEQyVKXsOiOY/wBbxRbK/t+A5jzbIcx+EhhHNKtLvQOOHmiq+yodk7rLnkGpe9OheArvghYxymoDWsX/rG9KBmiIrL5KpXlct6hsPFy7b+n1CFnMQJim15wz3+aHbEmwCfETPEtQ4jHFRWzazpa6n1Ein6wXBe/4T5GAVDll6dz1L+adEPZ/qjXiNZ4fPAc+6jc/8LfSrCzPinuF+wY9aCYHGDr6wmGE6SNRY3/lbOSjuxqhC34Q5nWLtZ6hKWXY8983GYGK/1dzojxmxhp280GdSbyHT3X3JgNaGGihjKTfzKRpJaJBDqQAeZSl3GzbTh2ucnFX3uoN8SRhmbeoSdgC1TsLF8+CWI14izLGgWIdr/O9KJmWgBnn79Lbb+0Yx2CplGHpd3c4oJzG90KDqTRFkKh3AGuY/iJGYr4rM9StUJU/OpxgAiz3GpQMSgms+cycEVxVFenuIFRw/yenIbSPA/Rzuphmf7Xp0/tmgJSxAvJ/fSX+w0p2Sy5GZjylrDNCJcmy1R+XpizADzULHRYQZO5aU0Zaa+6rWIDzdi5v8Lf1uDxdfRxVe47yphKtekX6M/s=
